["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]

p2p_market = [
    "src/p2p_resources_market/p2p_market.cairo",
]

asset_erc1155 = [
    "src/common/asset_erc1155.cairo",
]

nft_covered_contract = [
    "src/options_market/nft_covered_contract.cairo",
]
covered_call = [
    "src/options_market/covered_call.cairo",
]
["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src"]